'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Log
    Public Property Id As Integer
    Public Property [Date] As Date
    Public Property Thread As String
    Public Property Level As String
    Public Property Logger As String
    Public Property User As String
    Public Property Message As String
    Public Property Exception As String

End Class
