'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ProtonEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ProtonEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property tDocumentos() As DbSet(Of tDocumentos)
    Public Overridable Property tTipoProcessoExterno() As DbSet(Of tTipoProcessoExterno)
    Public Overridable Property tTipoRemetente() As DbSet(Of tTipoRemetente)
    Public Overridable Property vwOrgao() As DbSet(Of vwOrgao)
    Public Overridable Property vwTCs() As DbSet(Of vwTCs)
    Public Overridable Property EmailModelo() As DbSet(Of EmailModelo)
    Public Overridable Property Log() As DbSet(Of Log)

End Class
