'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tDocumentos
    Public Property Id As Integer
    Public Property Oficio As String
    Public Property IdTipoRemetente As Nullable(Of Integer)
    Public Property IdOrgao As Nullable(Of Integer)
    Public Property Remetente As String
    Public Property IdTipoProcessoExterno As Nullable(Of Integer)
    Public Property NumeroProcessoExterno As String
    Public Property TC As String
    Public Property Objeto As String
    Public Property Protocolo As String
    Public Property OficioTCM As String
    Public Property DataEntrada As Nullable(Of Date)
    Public Property Observacoes As String

    Public Overridable Property tTipoProcessoExterno As tTipoProcessoExterno
    Public Overridable Property tTipoRemetente As tTipoRemetente
    Public Overridable Property vwOrgao As vwOrgao

End Class
