'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tTipoProcessoExterno
    Public Property Id As Integer
    Public Property TipoProcessoExterno As String
    Public Property Mascara As String
    Public Property Status As String

    Public Overridable Property tDocumentos As ICollection(Of tDocumentos) = New HashSet(Of tDocumentos)

End Class
